class Major {
  final int? id; // Auto-generated by Supabase
  final String name;
  final int universityId;

  Major({
    this.id,
    required this.name,
    required this.universityId,
  });

  // Convert Major object to JSON for Supabase
  Map<String, dynamic> toJson() => {
        'name': name,
        'university_id': universityId,
      };

  // Create Major from JSON (e.g., when fetching from Supabase)
  factory Major.fromJson(Map<String, dynamic> json) => Major(
        id: json['id'] as int?,
        name: json['name'] as String,
        universityId: json['university_id'] as int,
      );
}