class Professor {
  final int? id; // Auto-generated by Supabase
  final String? name;
  final int? majorId;

  Professor({
    this.id,
    this.name,
    this.majorId,
  });

  // Convert Professor object to JSON for Supabase
  Map<String, dynamic> toJson() => {
        'name': name,
        'major_id': majorId,
      };

  // Create Professor from JSON (e.g., when fetching from Supabase)
  factory Professor.fromJson(Map<String, dynamic> json) => Professor(
        id: json['id'] as int?,
        name: json['name'] as String?,
        majorId: json['major_id'] as int?,
      );
}