class University {
  final int? id; // Auto-generated by Supabase
  final String name;
  final String shortName;
  final String uniType;
  final String uniLocation;

  University({
    this.id,
    required this.name,
    required this.shortName,
    required this.uniType,
    required this.uniLocation,
  });

  // Convert University object to JSON for Supabase
  Map<String, dynamic> toJson() => {
        'name': name,
        'short_name': shortName,
        'uni_type': uniType,
        'uni_location': uniLocation,
      };

  // Create University from JSON (e.g., when fetching from Supabase)
  factory University.fromJson(Map<String, dynamic> json) => University(
        id: json['id'] as int?,
        name: json['name'] as String,
        shortName: json['short_name'] as String,
        uniType: json['uni_type'] as String,
        uniLocation: json['uni_location'] as String,
      );
}